In [48]:
import pandas as pd

fish = pd.read_csv('data/Fish.csv')
fish.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [49]:
fish['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [50]:
cols = ['Weight', 'Length2', 'Length3', 'Height', 'Width']
fish_input = fish[cols]
fish_target = fish[['Species']]

In [51]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, test_size=0.2, random_state=42)

In [52]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [53]:
from sklearn.neighbors import KNeighborsClassifier

In [54]:
kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(train_scaled, train_target)
kn.score(test_scaled, test_target)

/Users/kimminsu/Desktop/DMF/ML/venv/lib/python3.12/site-packages/sklearn/neighbors/_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


0.875

In [55]:
test_scaled[:5]

array([[-0.88073193, -0.91322801, -1.0283757 , -0.91039055, -0.80235016],
       [-1.0649816 , -1.50683735, -1.54476888, -1.60562691, -1.94133485],
       [-0.53276816,  0.36821437,  0.31949804, -0.81779949, -0.64744725],
       [-0.33311681, -0.22539497, -0.2144    , -0.11171732, -0.11185911],
       [-0.67537626, -0.50806608, -0.58200193, -0.90554508, -0.49364992]])

In [56]:
kn.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Perch', 'Perch'], dtype=object)

In [57]:
kn.predict_proba(test_scaled[:5])

array([[0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.66666667, 0.        , 0.33333333,
        0.        , 0.        ],
       [0.        , 0.        , 0.66666667, 0.        , 0.33333333,
        0.        , 0.        ]])

In [58]:
bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')

train_bream_smelt = train_scaled[bream_smelt_indexes['Species']]
target_bream_smelt = train_target[bream_smelt_indexes['Species']]

In [59]:
from sklearn.linear_model import LogisticRegression

In [60]:
#이항분류
lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt)
lr.score(train_bream_smelt, target_bream_smelt)

/Users/kimminsu/Desktop/DMF/ML/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


1.0

In [61]:
lr.predict(train_bream_smelt[:5])

array(['Bream', 'Bream', 'Smelt', 'Bream', 'Bream'], dtype=object)

In [62]:
lr.predict_proba(train_bream_smelt)

array([[9.56366376e-01, 4.36336237e-02],
       [9.97957234e-01, 2.04276592e-03],
       [2.73510695e-02, 9.72648931e-01],
       [9.95561724e-01, 4.43827606e-03],
       [9.87581545e-01, 1.24184552e-02],
       [9.98018494e-01, 1.98150623e-03],
       [3.19644779e-02, 9.68035522e-01],
       [9.76083878e-01, 2.39161218e-02],
       [9.99613351e-01, 3.86649188e-04],
       [9.88465380e-01, 1.15346204e-02],
       [9.10795353e-01, 8.92046471e-02],
       [9.98692255e-01, 1.30774492e-03],
       [9.97969236e-01, 2.03076448e-03],
       [9.97357745e-01, 2.64225494e-03],
       [3.79119339e-02, 9.62088066e-01],
       [9.99664278e-01, 3.35722014e-04],
       [3.35347575e-02, 9.66465242e-01],
       [7.58137855e-02, 9.24186214e-01],
       [9.82274917e-01, 1.77250832e-02],
       [9.99485962e-01, 5.14038364e-04],
       [9.74193238e-01, 2.58067616e-02],
       [9.84013614e-01, 1.59863855e-02],
       [9.86717915e-01, 1.32820847e-02],
       [9.66701849e-01, 3.32981508e-02],
       [9.943311

In [63]:
lr.coef_

array([[-0.40431455, -0.57100332, -0.65957835, -1.02674369, -0.739561  ]])

In [64]:
# 다중분류
lr = LogisticRegression(C=20, max_iter=20)
lr.fit(train_scaled, train_target)
lr.score(train_scaled, train_target)

/Users/kimminsu/Desktop/DMF/ML/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/kimminsu/Desktop/DMF/ML/venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.905511811023622

In [65]:
lr.score(test_scaled, test_target)

0.90625

In [66]:
import numpy as np
np.round(lr.predict_proba(test_scaled[:5]), decimals=3)

array([[0.   , 0.012, 0.74 , 0.   , 0.237, 0.009, 0.002],
       [0.   , 0.002, 0.05 , 0.   , 0.006, 0.942, 0.   ],
       [0.   , 0.   , 0.019, 0.975, 0.006, 0.   , 0.   ],
       [0.006, 0.036, 0.335, 0.002, 0.512, 0.   , 0.108],
       [0.   , 0.   , 0.918, 0.001, 0.079, 0.001, 0.001]])

In [67]:
lr.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Roach', 'Perch'], dtype=object)

In [68]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [70]:
decision = lr.decision_function(test_scaled[:5])

In [74]:
#LogisticRegression은 자동적으로 softmax를 사용
from scipy.special import softmax

proba = softmax(decision, axis=1)
np.round(proba, decimals=3)

array([[0.   , 0.012, 0.74 , 0.   , 0.237, 0.009, 0.002],
       [0.   , 0.002, 0.05 , 0.   , 0.006, 0.942, 0.   ],
       [0.   , 0.   , 0.019, 0.975, 0.006, 0.   , 0.   ],
       [0.006, 0.036, 0.335, 0.002, 0.512, 0.   , 0.108],
       [0.   , 0.   , 0.918, 0.001, 0.079, 0.001, 0.001]])